### PR TITLE
Release v0.19.1

### PR DESCRIPTION
**Pull request by PrestonN**
This is an automated PR for the v0.19.1 release. This PR will be updated and merged once testing is complete.

### CODE REVIEW

**Comment by PrestonN** [comment]
bot, build

**Comment by bbhtt** [comment]
You have to wait for a fix in the linter to be deployed

**Comment by pm4rcin** [comment]
@PrestonN would be good opportunity to also update freedesktop sdk to 23.08 in this PR when problems are resolved.

**Comment by hfiguiere** [comment]
bot, build

**Pull request merged**
